version: '3.8'

services:
  quickchess_golang_server:
    build:
      context: ./server
      dockerfile: Dockerfile.golang.dev
    ports:
      - "8080:8080"

  quickchess_nextjs_web_client:
    build:
      context: ./client/web
      dockerfile: Dockerfile.nextjs.dev
    ports:
      - "3000:3000"
