version: '3.8'

services:
  golang_server:
    build:
      context: ./server
      dockerfile: Dockerfile.golang.dev
    ports:
      - "8080:8080"

  nextjs_web_client:
    build:
      context: ./client/web
      dockerfile: Dockerfile.nextjs.dev
    ports:
      - "3000:3000"

  db_postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=quickchess@admin
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
    driver: local
